-- require("abhi.plugins.nightfly")
-- require("abhi.plugins.gruvbox")
require("abhi.plugins.tokyonight")
require("abhi.plugins.lualine")
require("abhi.plugins.bufferline")
require("abhi.plugins.nvim-tree")
require("abhi.plugins.treesitter")
require("abhi.plugins.telescope")
require("abhi.plugins.lsp_config")
require("abhi.plugins.which-key")
require("abhi.plugins.completions")
require("abhi.plugins.null")
require("abhi.plugins.alpha")
require("abhi.plugins.dap")
require("abhi.plugins.comment")
require("abhi.plugins.autopairs")
require("abhi.plugins.indent")
require("abhi.plugins.gitsigns")
require("abhi.plugins.refactor")
require("abhi.plugins.todo")
require("abhi.plugins.trouble")
